### ISSUE TITLE
tests: change invocation of modulelint

### ISSUE THREAD

**Issue by jscotka** [container-images/container-image-template-old#12]
there is changed way where are __modulelint__ tests.
in previous way there was just one file `modulelint.py`
It changed to modulelint directory, because of increasing complexity of one file.
so please replace `modulelint.py` by `modulelint/*`

**Comment by TomasTomecek** [comment]
Can you submit a patch? or @phracek what that be something you can fix?

**Comment by jscotka** [comment]
sure, PR created:
https://github.com/container-images/container-image-template/pull/13

**Comment by TomasTomecek** [comment]
#13 is merged
