### ISSUE TITLE
Container Application Configuration Guideline [RFC]

### ISSUE THREAD

**Issue by LorbusChris** [container-images/container-image-template-old#36]
I am not sure whether this has been discussed here earlier. If there already are best practices in place for this, please provide some info and feel free to close this issue.

**Q: How to pass custom configuration to the containerized application?**

I've come across a few different ways of configuring a containerized app, e.g.:
* Build Time
  * rely on defaults provided by rpm installation
  * copy config file
  * otherwise hardcoded
* Run Time
  * pass env vars to CLI 
  * pass env vars to custom script
  * mount config file in container volume

My 2 cents:
I personally prefer the config volume option as it gives me the most fine grained control over the application. This is especially true for apps that require a rather complex config, like e.g. postfix.
I believe it is also the recommended way in the K8s/Openshift world, where changes in mounted ConfigMaps and Secrets may trigger a reconfigured deployment. 

Therefore, I propose adding a guideline for Modularity packagers, so everyone can be on the same page. It may look something like this, for example:

* Sensible default configuration should be provided by the rpm at container build time.
* Custom/further configuration should be done by mounting configuration file(s) in volume(s) at container run time.

What do you think? Let me know, please! Request for Comments :smiley: 

Cheers,
Chris

**Comment by LorbusChris** [comment]
There may be giudelines in place for this already:
From [Standalone Containers](https://docs.pagure.org/modularity/development/building-modules/standalone-containers.html) in the Modularity docs:

> Requirements¶
> * Only a single instance of a standalone container is supported to run on a host (installation of the same container image twice won’t be successful).
> * Services are managed via systemd unit files.
> * Containers are installed to a system.
> * There is no dedicated network namespace.
> * **Configuration is stored in the same locations on the host as a non-containerized service.**
> * **Persistent data can be found in the same locations on the host as for non-containerized service.**
> * **Service presence, configuration and persistent data are tracked by the RPM database.**
> * Application lifecycle is close to services deployed as RPMs.
> * Some commands may need to be executed inside the container since the service is not running directly on host.

I don't like the idea of all (or even most) config being baked in at build time. I also like to avoid custom config scripts wherever possible. The nginx container image seems to be a good example for that. However, instead of doing
```
COPY files/nginx.conf /etc/nginx/nginx.conf
```
in the Dockerfile, this could be done in the systemd unit file on the host: 
```
[Service]
ExecStartPre=/usr/bin/docker create -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf/:ro ...
```
Providing the config as a volume from the same location the application would use for its config when running non-containerized.

PS: The same would also be true for Certs and other Secrets, that need mounting and/or renewal.
PPS: Sorry for the spam.

**Comment by TomasTomecek** [comment]
Hey Chris! You are right on track. We've been battling configuration past few weeks. We've managed to write these two blog posts to address the problem:
 * [Configuring Containerized Services](https://developers.redhat.com/blog/2017/07/10/configuring-containerized-services/)
 * [Flexible Container Images with OpenShift](https://blog.openshift.com/flexible-container-images/)

This is what we plan to do right now:

1. Update [Container Best Practices](https://github.com/projectatomic/container-best-practices) with the info from the blog posts mentioned above.
2. Evolve the best practices for configuring containerized services to use [s2i](https://github.com/openshift/source-to-image) (@rpitonak is investigating work of [Software Collections team](https://github.com/sclorg/) on their [mongodb container image](https://github.com/sclorg/mongodb-container/)).

Regarding standalone container spec you are linking, we didn't manage to finish it, yet. It's actually very close to [system containers](http://www.projectatomic.io/blog/2016/09/intro-to-system-containers/).

Chris, once Rado (@rpitonak) comes with a prototype, would you be willing to take a look and tell us what you think?


To comment on your proposal a bit: as I said, we've kind of put the standalone containers on back burner. So I can't comment much there.

Thank you for your interest!

**Comment by LorbusChris** [comment]
Thanks Tomas! I'm reading through it now.

I'll happily give feedback about the prototype and help upstream the necessary changes to the other container-repos, once the Guidelines have been settled.
